DATASETS_PATH = "./dataset"

ENTROPY_DS_PATH = f'{DATASETS_PATH}/Entropy/'
RL_DS_PATH = f'{DATASETS_PATH}/RL/'
ENSEMBLES_DS_PATH = f'{DATASETS_PATH}/Ensembes/'

ENTROPY_CHROMA_PATH = f'{DATASETS_PATH}/Entropy/chromadb/'
RL_CHROMA_PATH = f'{DATASETS_PATH}/RL/chromadb/'
ENSEMBLES_CHROMA_PATH = f'{DATASETS_PATH}/Ensembes/chromadb/'
